[package]
name = "regexes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
once_cell = "1.9.0"
regex = "1.5.5"
